CREATE TABLE DEPARTAMENTO(
	CLAVE_DEPTO NUMBER(1),
	NOMBRE VARCHAR(30) NOT NULL,
	PRESUPUESTO NUMBER(5) NOT NULL,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (CLAVE_DEPTO)
);
CREATE TABLE EMPLEADOS(
	CLAVEEMPLEADO VARCHAR(5),
	NOMBRE VARCHAR(30) NOT NULL,
	AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    CLAVEDEPTO NUMBER(1)NOT NULL,
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (CLAVEEMPLEADO),
    CONSTRAINT FK_EMPLEADOS FOREIGN KEY CLAVEDEPTO REFERENCES DEPARTAMENTO(CLAVE_DEPTO)
);

INSERT INTO EMPLEADOS VALUES('EMP01', 'ARMANDO', 'LOPEZ', 2);
INSERT INTO EMPLEADOS VALUES('EMP02', 'TATIANA', 'VARGAS', 1);
INSERT INTO EMPLEADOS VALUES('EMP03', 'LAURA', 'GARCIA', 3);
INSERT INTO EMPLEADOS VALUES('EMP04', 'JUAN', 'PEREZ', 4);
INSERT INTO EMPLEADOS VALUES('EMP05', 'IVAN', 'LOPEZ', 4);
INSERT INTO EMPLEADOS VALUES('EMP06', 'MARGARITA', 'HERNANDEZ', 1);
INSERT INTO EMPLEADOS VALUES('EMP07', 'JESUS', 'PEREZ', 3);
INSERT INTO EMPLEADOS VALUES('EMP08', 'TOÑO', 'FLORES', 2);
INSERT INTO EMPLEADOS VALUES('EMP09', 'JUAN', 'LOPEZ', 4);
INSERT INTO EMPLEADOS VALUES('EMP10', 'JOSE', 'HERNANDEZ', 5);

INSERT INTO DEPARTAMENTO VALUES(1, 'PERSONAL', 80000);
INSERT INTO DEPARTAMENTO VALUES(2, 'ALMACEN', 70000);
INSERT INTO DEPARTAMENTO VALUES(3, 'CONTABILIDAD', 60000);
INSERT INTO DEPARTAMENTO VALUES(4, 'MANUFACTURA', 50000);
INSERT INTO DEPARTAMENTO VALUES(5, 'EMPAQUE', 30000);