CREATE TABLE OFICINA(
	COD_OFICINA NUMBER(4),
	DIRECCION VARCHAR(30) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	DNIDIR VARCHAR(9) NOT NULL,
	DNICOM VARCHAR(9) NOT NULL,
	CONSTRAINT pk_oficina PRIMARY KEY(COD_OFICINA),
	CONSTRAINT fk_director FOREIGN KEY(DNIDIR) REFERENCES DIRECTOR(DNI) ON DELETE CASCADE,
	CONSTRAINT fk_comercial FOREIGN KEY(DNICOM) REFERENCES COMERCIAL(DNI) ON DELETE CASCADE,
	CONSTRAINT ck_ofcina CHECK (LENGTH(telefono)=9)
);
CREATE TABLE COMERCIAL(
	DNI VARCHAR(9),
	COMISION NUMBER(3) NOT NULL,
	COD_OFICINA NUMBER(4) NOT NULL,
	CONSTRAINT pk_comercial PRIMARY KEY(DNI),
	CONSTRAINT fk_datospersonales FOREIGN KEY(DNI) REFERENCES DATOSPERSONALES(DNI) ON DELETE CASCADE,
	CONSTRAINT fk_oficina FOREIGN KEY(COD_OFICINA) REFERENCES OFICINA(COD_OFICINA) ON DELETE CASCADE,
	CONSTRAINT ck_comision CHECK (comision>0 ADD comision<100)
);
CRETE TABLE VENDEDOR(
	DNI_VENDEDOR VARCHAR(9),
	TURNO VARCHAR(9) NOT NULL,
	CODOFICINA NUMBER(4) NOT NULL,
	CONSTRAINT pk_vendedor PRIMARY KEY(DNI),
	CONSTRAINT fk_datospersonales FOREIGN KEY(DNI_VENDEDOR) REFERENCES DATOSPERSONALES(DNI) ON DELETE CASCADE,
	CONSTRAINT fk_oficina FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(COD_OFICINA) ON DELETE CASCADE,
	CONSTRAINT ck_turno CHECK TURNO IN('Maniana','Tarde','Noche')
);