CREATE TABLE SEDE(
	CODSEDE NUMBER(4) NOT NULL,
	NOMBRE VARCHAR(41) NOT NULL, 
	DIRECCION VARCHAR(40) NOT NULL,
	CONSTRAINT PK_SEDE PRIMARY KEY(CODSEDE)
);
CREATE TABLE DEPARTAMENTO(
	COD_SEDE NUMBER(4) NOT NULL,
	CODDEP NUMBER(4) NOT NULL,
	NOMBRE VARCHAR(41) NOT NULL,
	UBICACION VARCHAR(41) NOT NULL,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(COD_SEDE, CODDEP),
	CONSTRAINT FK_SEDE FOREIGN KEY(COD_SEDE) REFERENCES SEDE(CODSEDE) ON DELETE CASCADE
);
CREATE TABLE PROGRAMADOR(
	COD_SEDE_PROGRAMADOR NUMBER(4) NOT NULL,
	COD_DEP_PROGRAMADOR NUMBER (4) NOT NULL,
	SECUENCIA VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    CUENTA VARCHAR (35) NOT NULL,
    TELEFONO VARCHAR (35) NOT NULL,
    TIPO VARCHAR (35) NOT NULL,
    CONSTRAINT PK_PROGRAMADOR PRIMARY KEY(COD_SEDE_PROGRAMADOR, COD_DEP_PROGRAMADOR, SECUENCIA),
    CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(COD_DEP_PROGRAMADOR, COD_SEDE_PROGRAMADOR) REFERENCES DEPARTAMENTO(CODDEP, COD_SEDE) ON DELETE CASCADE
);
CREATE TABLE EQUIPO(
	CODEQUIPO NUMBER(4) NOT NULL,
	DESCRICION VARCHAR(40) NOT NULL,
	SECUENCIA VARCHAR(9) NOT NULL,
	COD_SEDE_PROGRAMADOR_EQUIPO NUMBER(4) NOT NULL,
	COD_DEP_PROGRAMADOR_EQUIPO NUMBER (4) NOT NULL,
	CONSTRAINT PK_EQUIPO PRIMARY KEY(CODEQUIPO),
	CONSTRAINT FK_PROGRAMADOR FOREIGN KEY(COD_SEDE_PROGRAMADOR_EQUIPO, COD_DEP_PROGRAMADOR_EQUIPO,SECUENCIA) REFERENCES PROGRAMADOR(COD_SEDE_PROGRAMADOR, COD_DEP_PROGRAMADOR, SECUENCIA) ON DELETE CASCADE
);
CREATE TABLE EQUIPOPROG(
	SECUENCIA_EQUIPOPROG VARCHAR(9) NOT NULL,
	CODEQUIPO_EQUIPOPROG NUMBER(4) NOT NULL,
	CONSTRAINT PK_EQUIPOPROG PRIMARY KEY(SECUENCIA_EQUIPOPROG, CODEQUIPO_EQUIPOPROG),
	CONSTRAINT FK_PROGRAMADOR_EQUIPO FOREIGN KEY(SECUENCIA_EQUIPOPROG) REFERENCES PROGRAMADOR(SECUENCIA) ON DELETE CASCADE,
	CONSTRAINT FK_EQUIPO_PROGRAMADOR FOREIGN KEY(CODEQUIPO_EQUIPOPROG) REFERENCES EQUIPO(CODEQUIPO) ON DELETE CASCADE
);
CREATE TABLE PROYECTO(
	CODEQUIPO NUMBER(4) NOT NULL,
	CODPROYECTO NUMBER(4) NOT NULL,
	DESCRIPCION VARCHAR(40) NOT NULL,
	FECHAINI DATE NOT NULL,
	FECHAFIN DATE NULL,
	CONSTRAINT PK_PROYECTO PRIMARY KEY(CODPROYECTO),
	CONSTRAINT FK_EQUIPO FOREIGN KEY(CODEQUIPO) REFERENCES EQUIPO(CODEQUIPO) ON DELETE CASCADE
);
ALTER TABLE PROGRAMADOR
ADD CONSTRAINT FK_PROGRAMADOR_MENTOR FOREIGN KEY(COD_SEDE_PROGRAMADOR, COD_DEP_PROGRAMADOR, SECUENCIA) REFERENCES PROGRAMADOR(COD_SEDE_PROGRAMADOR, COD_DEP_PROGRAMADOR,SECUENCIA)
ON DELETE CASCADE;
ALTER TABLE PROYECTO
ADD CONSTRAINT FK_PROYECTO_SUB FOREIGN KEY(CODPROYECTO) REFERENCES PROYECTO(CODPROYECTO)
ON DELETE CASCADE;