CREATE TABLE DIRECTOR(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(41) NOT NULL,
	PRAPELLIDO VARCHAR(30)NOT NULL,
	SGAPELLIDO VARCHAR(30),
	DOMICILIO VARCHAR(30) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	EMAIL VARCHAR(30),
	CONSTRAINT PK_DIRECTOR PRIMARY KEY(DNI)
);

CREATE TABLE SUPERMERCADO(
	CODSUP NUMBER(4),
	DIRECCION VARCHAR(30) NOT NULL,
	SUPERFICIE NUMBER(4) NOT NULL,
	ESALQUILER CHAR(1) NOT NULL,
	FECHA DATE,
	DNI VARCHAR(9)NOT NULL,
	CONSTRAINT PK_SUPERMERCADO PRIMARY KEY(CODSUP),
	CONSTRAINT FK_DIRECTOR FOREIGN KEY (DNI) REFERENCES DIRECTOR(DNI) ON DELETE CASCADE,
	CONSTRAINT CK_SUPERMERCADO CHECK(SUPERFICIE>0 AND ESALQUILER IN ('S', 'N', 'n','s'))
);

CREATE TABLE VENDEDOR(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(41) NOT NULL,
	PRAPELLIDO VARCHAR(30)NOT NULL,
	SGAPELLIDO VARCHAR(30),
	DOMICILIO VARCHAR(30) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	EMAIL VARCHAR(30),
	CODSUP NUMBER(4)NOT NULL,
	CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNI),
	CONSTRAINT FK_SUPERMERCADO FOREIGN KEY(CODSUP) REFERENCES SUPERMERCADO(CODSUP) ON DELETE CASCADE
);

CREATE TABLE CLIENTE(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(41) NOT NULL,
	PRAPELLIDO VARCHAR(30)NOT NULL,
	SGAPELLIDO VARCHAR(30),
	DOMICILIO VARCHAR(30) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	EMAIL VARCHAR(30),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI) 
);

CREATE TABLE VENTA(
	CODVENTA NUMBER(4),
	FECHA DATE,
	DNI_VENDEDOR VARCHAR(9) NOT NULL,
	DNI_CLIENTE VARCHAR(9) NOT NULL,
	CONSTRAINT PK_VENTA PRIMARY KEY (CODVENTA),
	CONSTRAINT FK_VENDEDOR FOREIGN KEY(DNI_VENDEDOR) REFERENCES VENDEDOR(DNI) ON DELETE CASCADE,
	CONSTRAINT FK_CLIENTE FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI) ON DELETE CASCADE
);

CREATE TABLE FAMILIA(
	CODFAMILIA NUMBER(4),
	CONSTRAINT PK_FAMILIA PRIMARY KEY (CODFAMILIA)
);

CREATE TABLE GENERO(
	CODGENERO NUMBER(4),
	CONSTRAINT PK_GENERO PRIMARY KEY (CODGENERO)
);

CREATE TABLE PRODUCTO(
	CODPRODUCTO NUMBER(4),
	DESCRIPCION VARCHAR(40) NOT NULL,
	DESCUENTO NUMBER (4,2) DEFAULT 0,
	IVA NUMBER (2),
	CODFAMILIA NUMBER (4),
	CODGENERO NUMBER(4),
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODPRODUCTO),
	CONSTRAINT FK_FAMILIA FOREIGN KEY (CODFAMILIA) REFERENCES FAMILIA(CODFAMILIA)ON DELETE SET NULL,
	CONSTRAINT FK_GENERO FOREIGN KEY (CODGENERO) REFERENCES GENERO(CODGENERO)ON DELETE SET NULL,
	CONSTRAINT CK_DESCUENTO CHECK(DESCUENTO>0 AND DESCUENTO<100),
	CONSTRAINT CK_IVA CHECK(IVA IN(4,10,21))
);

CREATE TABLE LINEAVENTA(
	NUMLINEA NUMBER(4),
	CODVENTA NUMBER(4)NOT NULL,
	CANTIDAD NUMBER(4)NOT NULL,
	CONSTRAINT PK_LINEAVENTA PRIMARY KEY (NUMLINEA, CODVENTA),
	CONSTRAINT FK_VENTA FOREIGN KEY (CODVENTA) REFERENCES VENTA(CODVENTA) ON DELETE CASCADE
);

CREATE TABLE DEVOLUCION(
	CODVENTA NUMBER(4),
	CODFAMILIA NUMBER(4),
	NUMLINEA NUMBER(4),
	FECHA DATE,
	ESTADO CHAR(1) NOT NULL,
	TIPODEV NUMBER(1)NOT NULL,
	CONSTRAINT PK_DEVOLUCION PRIMARY KEY (CODVENTA, NUMLINEA, FECHA),
	CONSTRAINT FK_LINEAVENTA FOREIGN KEY (CODVENTA, NUMLINEA) REFERENCES LINEAVENTA(CODVENTA,NUMLINEA) ON DELETE CASCADE
);

CREATE TABLE PRECIO(
	CODPRODUCTO NUMBER(4),
	FECHA DATE,
	PRECIO NUMBER(6,2) NOT NULL,
	CONSTRAINT PK_PRECIO PRIMARY KEY (CODPRODUCTO, FECHA),
	CONSTRAINT FK_PRODUCTO FOREIGN KEY (CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO) ON DELETE CASCADE
);

ALTER TABLE DIRECTOR ADD CONSTRAINT UK_TELEFONO_DIRECTOR UNIQUE(TELEFONO);
ALTER TABLE DIRECTOR ADD CONSTRAINT UK_EMAIL_DIRECTOR UNIQUE(EMAIL);

ALTER TABLE VENDEDOR ADD CONSTRAINT UK_TELEFONO_VENDEDOR UNIQUE(TELEFONO);
ALTER TABLE VENDEDOR ADD CONSTRAINT UK_EMAIL_VENDEDOR UNIQUE(EMAIL);

ALTER TABLE CLIENTE ADD CONSTRAINT UK_TELEFONO_CLIENTE UNIQUE(TELEFONO);
ALTER TABLE CLIENTE ADD CONSTRAINT UK_EMAIL_CLIENTE UNIQUE(EMAIL);

ALTER TABLE DIRECTOR ADD CONSTRAINT CK_TELEFONO_DIRECTOR CHECK(TELEFONO>99999999 AND TELEFONO<=999999999);
ALTER TABLE DIRECTOR ADD CONSTRAINT CK_TELEFONO_VENDEDOR CHECK(TELEFONO>99999999 AND TELEFONO<=999999999);
ALTER TABLE DIRECTOR ADD CONSTRAINT CK_TELEFONO_CLIENTE CHECK(TELEFONO>99999999 AND TELEFONO<=999999999);

ALTER TABLE VENTA ADD CONSTRAINT CK_DNI CHECK NOT(DNI_VENDEDOR=DNI_CLIENTE);

ALTER TABLE PRODUCTO ADD CONSTRAINT UK_DESCRIPCION UNIQUE(DESCRIPCION);

ALTER TABLE LINEAVENTA ADD CONSTRAINT CK_NUMLINEA CHECK(NUMLINEA>=1 AND NUMLINEA<=99);