CREATE TABLE PROFESOR(
    DNI  VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    CUENTA VARCHAR (35) NOT NULL,
    TELEFONO VARCHAR (35) NOT NULL,
    CONSTRAINT PK_PROFESOR PRIMARY KEY(DNI)
    );
CREATE TABLE CICLOFORM(
    CODCICLO NUMBER(4)NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    TIPO VARCHAR(41) NOT NULL,
    CONSTRAINT PK_CICLOFORM PRIMARY KEY(CODCICLO)
    );
CREATE TABLE ASIGNATURA(
    CODASIG NUMBER(4)NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    NUMHORAS NUMBER(3) NOT NULL,
    DNI_PROFESOR VARCHAR(9) NOT NULL,
    CODCICLO_CICLOFORM NUMBER(4) NOT NULL,
    CONSTRAINT FK_PROFESOR_ASIGNATURA FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESOR(DNI),
    CONSTRAINT FK_CICLOFORM FOREIGN KEY(CODCICLO_CICLOFORM) REFERENCES CICLOFORM(CODCICLO),
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY(CODASIG)
    );
CREATE TABLE IDIOMA(
    CODIDIOMA NUMBER(4)NOT NULL,
    DESCRIPCION VARCHAR(41) NOT NULL,
    CONSTRAINT PK_IDIOMA PRIMARY KEY(CODIDIOMA)
    );
CREATE TABLE ALUMNO(
    DNI  VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    EMAIL VARCHAR (35) NOT NULL,
    TELEFONO VARCHAR (35) NOT NULL,
    CODIDIOMA_IDIOMA NUMBER(4) NULL,
    CONSTRAINT PK_ALUMNO PRIMARY KEY(DNI),
    CONSTRAINT FK_IDIOMA FOREIGN KEY(CODIDIOMA_IDIOMA) REFERENCES IDIOMA(CODIDIOMA)
    );
CREATE TABLE MATRICULA(
    DNI_ALUMNO VARCHAR(9) NOT NULL,
    CODASIG NUMBER(4) NOT NULL,
    CONSTRAINT PK_MATRICULA PRIMARY KEY(CODASIG, DNI_ALUMNO),
    CONSTRAINT FK_ALUMNO FOREIGN KEY(DNI_ALUMNO) REFERENCES ALUMNO(DNI),
    CONSTRAINT FK_ASIGNATURA FOREIGN KEY(CODASIG) REFERENCES ASIGNATURA(CODASIG)
    );
CREATE TABLE IDIOMASPROF(
    CODIDIOMA  NUMBER(4)NOT NULL,
    DNI_PROFESOR_IDIOMA VARCHAR(9)NOT NULL,
    CONSTRAINT PK_IDIOMASPROF PRIMARY KEY(CODIDIOMA, DNI_PROFESOR_IDIOMA),
    CONSTRAINT FK_PROFESOR_IDIOMAS FOREIGN KEY(DNI_PROFESOR_IDIOMA) REFERENCES PROFESOR(DNI),
    CONSTRAINT FK_IDIOMA FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA(CODIDIOMA)
    );