CREATE TABLE DIRECTOR(
	DNI  VARCHAR(9)NOT NULL,
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    EMAIL VARCHAR (35) NULL,
    TELEFONO VARCHAR (35) NOT NULL,
    CONSTRAINT PK_PROFESOR PRIMARY KEY(DNI)
);
CREATE TABLE SUPERMERCADO(
	CODSUP NUMBER(4),
	DIRECCION VARCHAR(30) NOT NULL,
	SUPERFICIE NUMBER(4) NOT NULL,
	ESALQUILER CHAR(1) NOT NULL,
	FECHA DATE,
	DNI VARCHAR(9)NOT NULL,
	CONSTRAINT PK_SUPERMERCADO PRIMARY KEY(CODSUP),
	CONSTRAINT FK_DIRECTOR FOREIGN KEY (DNI) REFERENCES DIRECTOR(DNI)
);
CREATE TABLE VENDEDOR(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(41) NOT NULL,
	PRAPELLIDO VARCHAR(30)NOT NULL,
	SGAPELLIDO VARCHAR(30),
	DOMICILIO VARCHAR(30) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	EMAIL VARCHAR(30),
	CODSUP NUMBER(4)NOT NULL,
	CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNI),
	CONSTRAINT FK_SUPERMERCADO FOREIGN KEY(CODSUP) REFERENCES SUPERMERCADO(CODSUP)
);
CREATE TABLE CLIENTE(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(41) NOT NULL,
	PRAPELLIDO VARCHAR(30)NOT NULL,
	SGAPELLIDO VARCHAR(30),
	DOMICILIO VARCHAR(30) NOT NULL,
	TELEFONO NUMBER(9) NOT NULL,
	EMAIL VARCHAR(30),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI) 
);
CREATE TABLE VENTA(
	CODVENTA NUMBER(4),
	FECHA DATE,
	DNI_VENDEDOR VARCHAR(9) NOT NULL,
	DNI_CLIENTE VARCHAR(9) NOT NULL,
	CONSTRAINT PK_VENTA PRIMARY KEY (CODVENTA),
	CONSTRAINT FK_VENDEDOR FOREIGN KEY(DNI_VENDEDOR) REFERENCES VENDEDOR(DNI),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI)
);
CREATE TABLE PRODUCTO(
	CODPRODUCTO NUMBER(4),
	DESCRIPCION VARCHAR(40) NOT NULL,
	DESCUENTO NUMBER (4,2) DEFAULT 0,
	IVA NUMBER (2),
	FAMILIA VARCHAR (30)NOT NULL,
	GENERO VARCHAR(30)NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODPRODUCTO)
);
CREATE TABLE PRECIO(
	CODPRODUCTO NUMBER(4),
	FECHA DATE,
	PRECIO NUMBER(6,2) NOT NULL,
	CONSTRAINT PK_PRECIO PRIMARY KEY (CODPRODUCTO, FECHA),
	CONSTRAINT FK_PRODUCTO FOREIGN KEY (CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO)
);
CREATE TABLE LINEAVENTA(
	NUMLINEA NUMBER(4),
	CODVENTA NUMBER(4)NOT NULL,
	CANTIDAD NUMBER(4)NOT NULL,
	CONSTRAINT PK_LINEAVENTA PRIMARY KEY (NUMLINEA, CODVENTA),
	CONSTRAINT FK_VENTA FOREIGN KEY (CODVENTA) REFERENCES VENTA(CODVENTA)
);
CREATE TABLE DEVOLUCION(
	CODVENTA NUMBER(4),
	CODFAMILIA NUMBER(4),
	NUMLINEA NUMBER(4),
	FECHA DATE,
	ESTADO CHAR(1) NOT NULL,
	TIPODEV NUMBER(1)NOT NULL,
	CONSTRAINT PK_DEVOLUCION PRIMARY KEY (CODVENTA, NUMLINEA, FECHA),
	CONSTRAINT FK_LINEAVENTA FOREIGN KEY (CODVENTA, NUMLINEA) REFERENCES LINEAVENTA(CODVENTA,NUMLINEA)
);
