--EJERCICIO 5o6
--A--
SELECT DNI FROM PROFESOR JOIN DEPARTAMENTO ON PROFESOR.DNI=DEPARTAMENTO.DNI WHERE DEPARTAMENTO.NOMBRE IN ("iNFORMATICA", 'COMUNICACIONES');
--B--
SELECT NOMBRE, PRAPELLIDO FROM ALUMNO JOIN ALUMBIL ON ALUMNO.DNI=ALUMBIL.DNI WHERE ALUMBIL.LUGAR IN('MADRID','BARCELONA');
--C--
SELECT ALUMNO.NOMBRE, ALUMNO.PRAPELLIDO, ALUMNO.SGAPELLIDO FROM ALUMNO JOIN MATRICULA ON ALUMNO.DNI = MATRICULA.DNI JOIN ASIGNATURA ON MATRICULA.CODASIG = ASIGNATURA.CODASIG WHERE ALUMNO.NOMBRE IN ('BASES DE DATOS', 'ACCESO A DATOS');
--D--
SELECT ALUMNO.NOMBRE, ALUMNO.PRAPELLIDO, ALUMNO.SGAPELLIDO FROM ALUMNO JOIN MATRICULA ON ALUMNO.DNI = MATRICULA.DNI JOIN ASIGNATURA ON MATRICULA.CODASIG = ASIGNATURA.CODASIG JOIN CICLO ON ASIGNATURA.CODCF = CICLO.CODCF WHERE CICLO.SIGLAS = 'DAM' AND MATRICULA.NOTA >= 5;
--E--
SELECT ASIGNATURA.NOMBRE FROM ALUMNO JOIN MATRICULA ON ALUMNO.DNI = MATRICULA.DNI JOIN ASIGNATURA ON MATRICULA.CODASIG = ASIGNATURA.CODASIG JOIN IMPARTE ON ASIGNATURA.CODASIG = IMPARTE.CODASIG JOIN PROFESOR ON IMPARTE.DNI = PROFESOR.DNI JOIN DEPARTAMENTO ON PROFESOR.CODDEP = DEPARTAMENTO.CODDEP JOIN CICLO ON ASIGNATURA.CODCF = CICLO.CODCF WHERE NH > 100 AND CICLO.SIGLAS = 'DAM' AND CICLO.NOMBRE = 'Informatica y Comunicaciones' AND MATRICULA.CURSO = 2023;