ALTER TABLE DATOSPERSONALES ADD CONSTRAINT CK_TIPO CHECK TIPO IN('N', 'D');
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT CK_NUMPROF CHECK(NUMPROF>=1 AND NUMPROF<=30);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT UK_DESCRIPCION UNIQUE(DESCRIPCION);
ALTER TABLE DOCTORANDO ADD CONSTRAINT CK_FECHACOMIENZO CHECK NOT(FECHACOMIENZO<'1/1/2000' AND FECHACOMIENZO>DATE);
ALTER TABLE DOCTOR ADD CONSTRAINT UK_TITULO UNIQUE(TITULO);
ALTER TABLE DOCTOR MODIFY TITULO CHECK(10);
ALTER TABLE DOCTOR ADD CONSTRAINT CK_CALIFICACION CHECK(CALIFICACION>=0 AND CALIFICACION<=10);
ALTER TABLE CURSO ADD CONSTRAINT CK_DURACION CHECK(DURACION<10 AND DURACION<500);

ALTER TABLE AULAS ADD CONSTRAINT FK_CODCURSO FOREIGN KEY(CODCURSO) REFERENCES CURSO(CODCURSO);
ALTER TABLE DOCTORANDO ADD CONSTRAINT FK_CODCURSO FOREIGN KEY(CODCURSO) REFERENCES CURSO(CODCURSO);
ALTER TABLE AULAS ADD CONSTRAINT CK_TIPO CHECK TIPO IN('AULA DE PRACTICAS', 'AULA AUDIOVISUAL', 'AULA GRUPOS PEQUEÑOS', 'AULA NORMAL', 'AULA MAGNA');

