Fabricante(P-CodFab, Fabricante)
Marca(P-CodMarca, Marca)
Vehículo(P-CodVeh, Modelo, Tipo, Color, F-CodFab -> Fabricante, F-CodMarca -> Marca)
Cliente(P-dni, Nombre, prApellido, N-sgApellido, domicilio, NumTarjeta)
Oficina(P-CodOficina, Domicilio, Telefono)
Curso(P-CodCurso, Descripcion, numHoras, Fecha)
Empleado(P-dni, Nombre, prApellido, N-sgApellido, Domicilio, NumCuenta)
CursoEmpl(PF-dni -> Empleado, PF-CodCurso -> Curso)
Alquiler(P-CodAlquiler, Fecha, NumDias, KmActual, KmEntrega, F-dni -> Empleado, F-dni
->Cliente, F-CodVehiculo -> Vehiculo)
OficinasAlq(PF-CodOficina -> oficina, PF-CodAlquiler -> Alquiler)

CREATE TABLE FABRICANTE(
	CODFAB NUMBER(4),
	FABRICANTE VARCHAR(30)NOT NULL,
	CONSTRAINT PK_FABRICANTE PRIMARY KEY(CODFAB)
);
CREATE TABLE MARCA(
	CODMARCA NUMBER(4),
	MARCA VARCHAR(30)NOT NULL,
	CONSTRAINT PK_MARCA PRIMARY KEY(CODMARCA)
);
CREATE TABLE VEHICULO(
	CODVEH NUMBER(4),
	MODELO VARCHAR(30)NOT NULL,
	TIPO VARCHAR(30)NOT NULL,
	COLOR VARCHAR(15)NOT NULL,
	CODFAB NUMBER(4)NOT NULL,
	CODMARCA NUMBER(4)NOT NULL,
	CONSTRAINT PK_VEHICULO PRIMARY KEY(CODVEH),
	CONSTRAINT FK_FABRICANTE FOREIGN KEY(CODFAB) REFERENCES FABRICANTE(CODFAB),
	CONSTRAINT FK_MARCA FOREIGN KEY(CODMARCA) REFERENCES MARCA(CODMARCA)
);
CREATE TABLE CLIENTE(
	DNI  VARCHAR(9),
    NOMBRE VARCHAR(41) NOT NULL,
    AP1 VARCHAR(35) NOT NULL,
    AP2 VARCHAR(35) NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    NUMTARJETA NUMBER(16)NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI)
);
CREATE TABLE OFICINA(
	CODOFICINA NUMBER(4),
	DOMICILIO VARCHAR(30)NOT NULL,
	TELEFONO NUMBER(4)NOT NULL,
	CONSTRAINT PK_OFICINA PRIMARY KEY(CODOFICINA)
);
CREATE TABLE CURSO(
	CODCURSO NUMBER(4),
	DESCRIPCION VARCHAR(35)NOT NULL,
	NUMHORAS NUMBER(3)NOT NULL,
	FECHA DATE,
	CONSTRAINT PK_CURSO PRIMARY KEY(CODCURSO)
);
CREATE TABLE EMPLEADO(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(30)NOT NULL,
	AP1 VARCHAR(30) NOT NULL,
	AP2 VARCHAR(35) NULL,
	DOMICILIO VARCHAR(35)NOT NULL, 
	NUMCUENTA NUMBER()NOT NULL,
	CONSTRAINT PK_EMPLEADO PRIMARY KEY(DNI)
);
CREATE TABLE CURSOEMPLEADO(
	DNI VARCHAR(9),
	CODCURSO NUMBER(4),
	CONSTRAINT PK_CURSOEMPLEADO PRIMARY KEY(DNI, CODCURSO),
	CONSTRAINT FK_EMPLEADO FOREIGN KEY(DNI) REFERENCES EMPLEADO(DNI),
	CONSTRAINT FK_CURSO FOREIGN KEY(CODCURSO) REFERENCES CURSO(CODCURSO)
);
CREATE TABLE ALQUILER(
	CODALQUILER NUMBER(4),
	FECHA DATE,
	NUMDIAS NUMBER(3)NOT NULL,
	KMACTUAL NUMBER(6)NOT NULL,
	KMENTREGA NUMBER(6)NOT NULL,
	DNI_EMPLEADO VARCHAR(9)NOT NULL,
	DNI_CLIENTE VARCHAR(9)NOT NULL,
	CODVEHICULO NUMBER(4)NOT NULL,
	CONSTRAINT PK_ALQUILER PRIMARY KEY(CODALQUILER),
	CONSTRAINT FK_EMPLEADOALQUILER FOREIGN KEY(DNI_EMPLEADO) REFERENCES EMPLEADO(DNI),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI),
	CONSTRAINT FK_VEHICULO FOREIGN KEY(CODVEHICULO) REFERENCES VEHICULO(CODVEHICULO)
);
CREATE TABLE OFICINASALQUILER(
	CODOFICINA NUMBER(4),
	CODALQUILER NUMBER(4),
	CONSTRAINT PK_OFICINASALQUILER PRIMARY KEY(CODOFICINA, CODALQUILER),
	CONSTRAINT FK_OFICINA FOREIGN KEY(CODOFICINA) REFERENCES OFICINA(CODOFICINA),
	CONSTRAINT FK_ALQUILER FOREIGN KEY(CODALQUILER) REFERENCES ALQUILER(CODALQUILER)
);