CREATE TABLE TIPODP (
	CODTIPO VARCHAR(41),
	DESCRIPCION VARCHAR(41) NOT NULL,
	CONSTRAINT pk_tipodp PRIMARY KEY (CODTIPO)
	);
ALTER TABLE DATOSPERSONALES ADD CONSTRAINT fk_tipodp FOREIGN KEY (TIPO) REFERENCES TIPODP(CODTIPO)

ALTER TABLE DIRECTOR ADD ANIOS NUMBER(2)NOT NULL;

ALTER TABLE COMERCIAL DROP COLUMN COMISION;

ALTER TABLE OFICINA ADD COMISION NUMBER(3)NOT NULL;

CREATE TABLE TURNO(
	CODTURNO NUMBER(4),
	DESCRIPCION VARCHAR(35)NOT NULL,
	CONSTRAINT PK_TURNO PRIMARY KEY(CODTURNO)
);

ALTER TABLE VENDEDOR ADD CONSTRAINT FK_TURNO FOREIGN KEY(CODTURNO) REFERENCES TURNO(CODTURNO);

CREATE TABLE TEMATICALIBRO(
	CODTEM NUMBER(4),
	DESCRIPCION VARCHAR(35)NOT NULL,
	CONSTRAINT PK_TEMATICALIBRO PRIMARY KEY(CODTEM)
);

ALTER TABLE LIBRO RENAME COLUMN PRECIO TO PRECIOACTUAL;
ALTER TABLE LIBRO ADD CONSTRAINT FK_TEMATICALIBRO FOREIGN KEY(CODTEM) REFERENCES TEMATICALIBRO(CODTEM);