CREATE TABLE FABRICANTES (
  ID NUMBER(3),
  NOMBRE VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_FABRICANTES PRIMARY KEY(ID)
);

CREATE TABLE PRODUCTOS (
  ID NUMBER(3),
  NOMBRE VARCHAR2(100) NOT NULL,
  PRECIO  NUMBER(6,2) NOT NULL,
  ID_FABRICANTE NUMBER(3) NOT NULL,
  CONSTRAINT PK_PRODUCTOS PRIMARY KEY(ID),
  FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTES(ID)
);
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(1, 'Asus');
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(2, 'Lenovo');
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(3, 'Hewlett-Packard');
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(4, 'Samsung');
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(5, 'Seagate');
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(6, 'Crucial');
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(7, 'Gigabyte');
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(8, 'Huawei');
INSERT INTO FABRICANTES(ID, NOMBRE) VALUES(9, 'Xiaomi');

INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(8, 'Portátil Yoga 520', 559, 2);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(9, 'Portátil Ideapd 320', 444, 2);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO PRODUCTOS(ID, NOMBRE, PRECIO, ID_FABRICANTE) VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);

--consultas de una tabla

SELECT NOMBRE FROM PRODUCTOS;
SELECT NOMBRE, PRECIO AS EUROS FROM PRODUCTOS;
SELECT UPPER(NOMBRE), PRECIO FROM PRODUCTOS;
SELECT LOWER(NOMBRE), PRECIO FROM PRODUCTOS;
SELECT NOMBRE, ROUND(PRECIO) FROM PRODUCTOS;
SELECT NOMBRE, TRUNC(PRECIO) FROM PRODUCTOS;
SELECT ID_FABRICANTE FROM FABRICANTES, PRODUCTOS WHERE FABRICANTES.ID=PRODUCTOS.ID_FABRICANTE;
SELECT DISTINCT(ID_FABRICANTE) FROM FABRICANTES, PRODUCTOS WHERE FABRICANTES.ID=PRODUCTOS.ID_FABRICANTE;
SELECT NOMBRE FROM FABRICANTES ORDER BY NOMBRE;
SELECT NOMBRE, PRECIO FROM PRODUCTOS ORDER BY(PRECIO, NOMBRE) LIMIT 1;
SELECT NOMBRE FROM PRODUCTOS WHERE PRECIO>=400;
SELECT NOMBRE FROM PRODUCTOS WHERE NOT PRECIO>=400;
SELECT * FROM PRODUCTOS WHERE PRECIO>80 AND PRECIO<300;
SELECT * FROM PRODUCTOS WHERE PRECIO BETWEEN 60 AND 200;
SELECT * FROM PRODUCTOS WHERE PRECIO>200 AND ID_FABRICANTE=6;
SELECT * FROM PRODUCTOS WHERE ID_FABRICANTE IN(1, 3, 5);
SELECT NOMBRE FROM FABRICANTES WHERE NOMBRE LIKE('S%');
SELECT NOMBRE FROM FABRICANTES WHERE NOMBRE LIKE('%e');
SELECT NOMBRE FROM FABRICANTES WHERE NOMBRE LIKE('%w%');


--CONSULTAS MULTITABLA
--INTERNA--
SELECT PRODUCTOS.NOMBRE, PRODUCTOS.PRECIO, FABRICANTES.NOMBRE FROM PRODUCTOS JOIN FABRICANTES USING(ID);
SELECT PRODUCTOS.NOMBRE, PRODUCTOS.PRECIO, FABRICANTES.NOMBRE FROM PRODUCTOS JOIN FABRICANTES USING(ID) ORDER BY(FABRICANTES.NOMBRE);
SELECT PRODUCTOS.ID, PRODUCTOS.NOMBRE, FABRICANTES.ID, FABRICANTES.NOMBRE FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.id;;
SELECT PRODUCTOS.NOMBRE, PRODUCTOS.PRECIO, FABRICANTES.NOMBRE FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE PRODUCTOS.PRECIO = (SELECT MIN(PRECIO) FROM PRODUCTOS);
SELECT PRODUCTOS.NOMBRE, PRODUCTOS.PRECIO, FABRICANTES.NOMBRE FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE PRODUCTOS.PRECIO = (SELECT MAX(precio) FROM productos);
SELECT * FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE FABRICANTES.NOMBRE='Lenovo';
SELECT * FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE FABRICANTES.NOMBRE='Crucial' AND PRODUCTOS.PRECIO>200;
SELECT * FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE FABRICANTES.NOMBRE='Asus' OR FABRICANTES.NOMBRE='Heulett-Packard' OR FABRICANTES.NOMBRE='Seagate';
SELECT * FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE FABRICANTES.NOMBRE IN('Asus', 'Heulett-Packard', 'Seagate');
SELECT NOMBRE, PRECIO FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE FABRICANTES.NOMBRE LIKE('%e');
SELECT NOMBRE, PRECIO FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE FABRICANTES.NOMBRE LIKE('%w%');
SELECT PRODUCTOS.NOMBRE, PRODUCTOS.PRECIO, FABRICANTES.NOMBRE FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE PRODUCTOS.PRECIO >=180 DESC, PRODUCTOS.NOMBRE ASC;

--EXTERNA--

SELECT * FROM FABRICANTES LEFT OUTER JOIN PRODUCTOS USING(ID);
SELECT * FROM FABRICANTES F LEFT JOIN PRODUCTOS P ON F.ID=P.ID WHERE P.ID IS NULL;
SELECT * FROM FABRICANTES F RIGHT JOIN PRODUCTOS P ON F.ID=P.ID WHERE F.ID IS NULL;

--CONSULTAS RESUMEN--

SELECT COUNT(*) FROM PRODUCTOS;
SELECT COUNT(*) FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE!=FABRICANTES.ID;
SELECT AVG(PRECIO) FROM PRODUCTOS;
SELECT MIN(PRECIO) FROM PRODUCTOS;
SELECT NOMBRE, PRECIO FROM PRODUCTO WHERE PRECIO=(SELECT MAX(PRECIO) FROM PRODUCTOS);
SELECT SUM(PRECIO) FROM PRODUCTOS;
SELECT COUNT(*) FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE=FABRICANTES.ID AND FABRICANTES.NOMBRE='Asus';
SELECT AVG(PRODUCTOS.PRECIO) FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE=FABRICANTES.ID AND FABRICANTES.NOMBRE='Asus';
SELECT MIN(PRODUCTOS.PRECIO) FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE=FABRICANTES.ID AND FABRICANTES.NOMBRE='Asus';
SELECT MAX(PRODUCTOS.PRECIO) FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE=FABRICANTES.ID AND FABRICANTES.NOMBRE='Asus';
SELECT SUM(PRODUCTOS.PRECIO) FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE=FABRICANTES.ID AND FABRICANTES.NOMBRE='Asus';
SELECT MAX(PRODUCTOS.PRECIO) MIN(PRODUCTOS.PRECIO) AVG(PRODUCTOS.PRECIO) COUNT(PRODUCTOS.NOMBRE) FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE=FABRICANTES.ID AND FABRICANTES.NOMBRE='Crucial';
SELECT COUNT(PRODUCTOS.NOMBRE) FROM PRODUCTOS GROUP BY(ID_FABRICANTE);
SELECT FABRICANTES.NOMBRE, MAX(PRODUCTOS.PRECIO), MIN(PRODUCTOS.PRECIO), AVG(PRODUCTOS.PRECIO) FROM FABRICANTES INNER JOIN PRODUCTOS ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID GROUP BY FABRICANTES.ID;
SELECT ID_FABRICANTE, MAX(PRECIO), MIN(PRECIO), AVG(PRECIO), COUNT(*) FROM PRODUCTOS GROUP BY ID_FABRICANTE HAVING AVG(PRECIO) > 200;
SELECT FABRICANTES.NOMBRE, MAX(PRODUCTOS.PRECIO), MIN(PRODUCTOS.PRECIO), AVG(PRODUCTOS.PRECIO), COUNT(*) FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID GROUP BY FABRICANTES.ID HAVING AVG(PRODUCTOS.PRECIO) > 200;
SELECT COUNT(*) FROM PRODUCTOS WHERE precio >= 180;
SELECT FABRICANTES.NOMBRE, COUNT(*) FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID WHERE PRODUCTOS.PRECIO >= 180 GROUP BY PRODUCTOS.ID_FABRICANTE;
SELECT AVG(PRECIO), ID_FABRICANTE FROM PRODUCTOS GROUP BY ID_FABRICANTE;
SELECT AVG(PRECIO), FABRICANTES.NOMBRE FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID GROUP BY FABRICANTES.NOMBRE;
SELECT AVG(PRECIO), FABRICANTES.NOMBRE FROM PRODUCTOS INNER JOIN FABRICANTES ON PRODUCTOS.ID_FABRICANTE = FABRICANTES.ID GROUP BY FABRICANTES.NOMBRE HAVING AVG(PRECIO) >= 150;
SELECT FABRICANTES.NOMBRE, COUNT(PRODUCTOS.ID_FABRICANTE) FROM FABRICANTES INNER JOIN PRODUCTOS ON FABRICANTES.ID = PRODUCTOS.ID_FABRICANTE GROUP BY FABRICANTES.ID HAVING COUNT(PRODUCTOS.ID) >= 2;

--SUBCONSULTAS WHERE--

SELECT * FROM PRODUCTOS WHERE ID_FABRICANTE=(SELECT ID FROM FABRICANTES WHERE NOMBRE='Lenovo');
SELECT * FROM PRODUCTOS WHERE PRECIO=(SELECT MAX(PRODUCTOS.PRECIO) FROM PRODUCTOS WHERE ID_FABRICANTE=(SELECT ID FROM FABRICANTES WHERE NOMBRE='Lenovo'));
SELECT NOMBRE FROM PRODUCTOS WHERE PRECIO=(SELECT MAX(P.PRECIO) FROM PRODUCTOS P WHERE P.ID_FABRICANTE=(SELECT ID FROM FABRICANTES F WHERE F.NOMBRE='Lenovo')) AND ID_FABRICANTE=(SELECT ID FROM FABRICANTES F WHERE F.NOMBRE='Lenovo');
SELECT NOMBRE FROM PRODUCTOS WHERE PRECIO=(SELECT MIN(P.PRECIO) FROM PRODUCTOS P WHERE P.ID_FABRICANTE=(SELECT ID FROM FABRICANTES F WHERE F.NOMBRE='Hewlett-Packard')) AND ID_FABRICANTE=(SELECT ID FROM FABRICANTES F WHERE F.NOMBRE='Hewlett-Packard');
SELECT * FROM PRODUCTOS WHERE PRECIO>=(SELECT MAX(P.PRECIO) FROM PRODUCTOS P WHERE P.ID_FABRICANTE=(SELECT ID FROM FABRICANTES F WHERE F.NOMBRE='Lenovo'));
SELECT * FROM PRODUCTOS WHERE PRECIO>(SELECT AVG(P.PRECIO) FROM PRODUCTOS P WHERE P.ID_FABRICANTE=(SELECT ID FROM FABRICANTES F WHERE F.NOMBRE='Asus')) AND ID_FABRICANTE=(SELECT ID FROM FABRICANTES F WHERE F.NOMBRE='Asus');

--SUBCONSULTAS ANY--

SELECT * FROM PRODUCTOS WHERE PRECIO >=ALL (SELECT PRECIO FROM PRODUCTOS);
SELECT * FROM PRODUCTOS WHERE PRECIO <=ALL (SELECT PRECIO FROM PRODUCTOS);
SELECT NOMBRE FROM FABRICANTES WHERE ID =ANY (SELECT ID_FABRICANTE FROM PRODUCTOS);
SELECT NOMBRE FROM FABRICANTES WHERE ID <>ANY (SELECT ID_FABRICANTE FROM PRODUCTOS);

--SUBCONSULTAS IN Y NOT IN--

SELECT NOMBRE FROM FABRICANTES WHERE ID IN(SELECT ID_FABRICANTE FROM PRODUCTOS WHERE ID=ID);
SELECT NOMBRE FROM FABRICANTES WHERE ID NOT IN(SELECT ID_FABRICANTE FROM PRODUCTOS WHERE ID=ID);

--SUBCONSULTAS CON EXISTS Y NOT EXISTS--

SELECT NOMBRE FROM FABRICANTES WHERE EXISTS(SELECT ID_FABRICANTE FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE=FABRICANTES.ID);
SELECT NOMBRE FROM FABRICANTES WHERE NOT EXISTS(SELECT ID_FABRICANTE FROM PRODUCTOS, FABRICANTES WHERE PRODUCTOS.ID_FABRICANTE=FABRICANTES.ID);

--SUBCONSULTAS CORRELACIONADAS--

SELECT F.NOMBRE, P.NOMBRE, P.PRECIO FROM FABRICANTES F, PRODUCTOS P WHERE P.ID_FABRICANTE=F.ID AND P.PRECIO=(SELECT MAX(PRECIO) FROM PRODUCTOS P2 WHERE P2.ID_FABRICANTE=F.ID);
SELECT * FROM PRODUCTOS P, FABRICANTES F WHERE P.ID_FABRICANTE=F.ID AND P.PRECIO>=(SELECT AVG(PRECIO) FROM PRODUCTOS P2 WHERE P2.ID_FABRICANTE=F.ID);
SELECT P.NOMBRE FROM PRODUCTOS P, FABRICANTES F WHERE F.NOMBRE='Lenovo' AND P.PRECIO=(SELECT MAX(PRECIO) FROM PRODUCTOS P2 WHERE P2.ID_FABRICANTE=F.ID);

--SUBCONSULTAS HAVING--

SELECT FABRICANTES.NOMBRE, COUNT(FABRICANTES.NOMBRE) FROM FABRICANTES, PRODUCTOS WHERE FABRICANTES.ID=PRODUCTOS.ID_FABRICANTE GROUP BY FABRICANTES.NOMBRE;